# Generated by Django 3.1 on 2020-08-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20200807_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date deleted'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date scheduled'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date sent'),
        ),
    ]
