# Generated by Django 3.1 on 2020-08-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20200807_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='deleted',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=240)),
                ('follow', models.DateTimeField(blank=True, null=True, verbose_name='date follow')),
                ('unfollow', models.DateTimeField(blank=True, null=True, verbose_name='date unfollow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.user')),
            ],
        ),
    ]
