# Generated by Django 3.1 on 2020-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20200810_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date did follow'),
        ),
        migrations.AddField(
            model_name='follow',
            name='unfollowed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date did unfollow'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follow',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date to follow'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='unfollow',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date to unfollow'),
        ),
    ]
