# Generated by Django 3.1 on 2020-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20200810_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='modified',
        ),
        migrations.AlterField(
            model_name='follow',
            name='username',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
