# Generated by Django 3.1 on 2020-08-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20200823_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rapidapi_key',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
