# Generated by Django 3.1 on 2020-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20200904_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='args',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
