# Generated by Django 3.1 on 2020-09-06 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import twitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_auto_20200904_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFollow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(default='screener.csv', max_length=255, validators=[twitter.models.validate_path], verbose_name='file path')),
                ('min_friend_follower_overlap', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='min friend follower overlap')),
                ('schedule', models.CharField(default='0 0 * * *', max_length=128, validators=[twitter.models.validate_schedule], verbose_name='crontab schedule')),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('over_hours', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='over hours')),
                ('unfollow_days', models.PositiveIntegerField(blank=True, default=2, null=True, verbose_name='unfollow days')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
